### ISSUE TITLE
Allow users to specify custom categories

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/top-issues-action#110]
### Is your feature request related to a problem? Please describe.

Currently, only the `top_issues`, `top_bugs`, `top_features` and `top_prs` categories are supported.

### Describe the solution you'd like

It would be great if people could specify additional categories that are created based on certain labels. For the https://github.com/anuraghazra/github-readme-stats repository, we would like to include issues with the `themes` label under a Top Themes section. Adding the following action inputs would allow this to be done.

```yml
name: Top issues action.
on:
  schedule:
  - cron:  '0 0 */1 * *'

jobs:
  ShowAndLabelTopIssues:
    name: Display and label top issues.
    runs-on: ubuntu-latest
    steps:
    - name: Run top issues action
      uses: rickstaa/top-issues-action@v1
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        custom_label: themes
        top_custom_label: ⭐ Top Themes
        top_custom_label_description: Top Themes PRs
        top_custom_label_colour: #0E8A16
```
